on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  buildMod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.16"
      
      - name: Install Modules and Build
        run: |
          bun i
          bun bun:build --ghSha=${{ github.sha }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          generate_release_notes: true
          files: |
            dist/skellycord.asar