on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  buildMod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "19.0.1"
      
      - name: Install Modules and Build
        run: |
          npm i
          npm run build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          tag_name: nightly
          generate_release_notes: true
          files: |
            build/skellycord/skellycord.min.js
            build/skellycord/preload.min.js
            build/skellycord/patcher.min.js