on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  buildMod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.16"
      
      - name: Install Modules and Build
        run: |
          bun i
          bun bun:build --ghSha=${{ github.sha }}
          cd types
          mv ../dist/skellycord.d.ts .
          npm --no-git-tag-version version patch
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          tag_name: nightly
          generate_release_notes: false
          files: |
            dist/skellycord.min.js
            dist/preload.min.js
            dist/patcher.min.js
            dist/skellycord.d.ts
      
      - name: Publish Types
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
          package: types
          